### ISSUE TITLE
Zip size almost lambda limit

### ISSUE THREAD

**Issue by stianlp** [pbegle/aws-lambda-py3.6-pandas-numpy#2]
Hi! First of all, I really appreciate that you zipped a lambda working numpy and pandas.

The zip is fairly large, and when I add a few more libraries I cannot upload it to lamda anymore. Looks like there is a size limit at 50MB. I am looking into how I can strip this zip a little bit, but if you or anyone else have a smaller zip I would be happy to use it :)

**Comment by 0xpetersatoshi** [comment]
You don't need to worry about file size. Simply add the file to an S3 bucket and then copy the S3 link. You can source it to lambda using that link.

**Comment by stianlp** [comment]
Yep, found this https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3 yesterday!
