### ISSUE TITLE
Unable to import module 'lambda_function': No module named 'lambda_function'

### ISSUE THREAD

**Issue by san73** [pbegle/aws-lambda-py3.6-pandas-numpy#4]
Hi,

Thanks for the information. But I am currently facing this issue, can anyone help me debug this please. 
I have uploaded lambda.zip file into S3 bucket with the lamda_function.py in it. 

Handler name : lambda_function.lambda_handler

The lamda_function.py file has the below code:

def lambda_handler(event, context):
    # TODO implement
    return 'Hello from Lambda'

Kindly help as I am in need of pandas library.

Regards,
Sanjeev

**Comment by AdrianEunoia** [comment]
Hey @san73, how did you resolve this problem? Im having the same error!

**Comment by haydenk** [comment]
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
